export enum ArtusXInjectEnum {
  Pipeline = 'ARTUSX_PIPELINE',
  Schedule = 'ARTUSX_SCHEDULE',

  // view engines
  EJS = 'ARTUSX_EJS',
  Nunjucks = 'ARTUSX_NUNJUCKS',

  // web framework
  Koa = 'ARTUSX_KOA',
  KoaRouter = 'ARTUSX_KOA_ROUTER',
  Nest = 'ARTUSX_NEST',
  Express = 'ARTUSX_EXPRESS',

  // database
  Redis = 'ARTUSX_REDIS',
  Sequelize = 'ARTUSX_SEQUELIZE',

  GRPC = 'ARTUSX_GRPC',
  Proxy = 'ARTUSX_PROXY',
  PPTR = 'ARTUSX_PPTR',
  Log4js = 'ARTUSX_LOG4JS',
  OpenAI = 'ARTUS_OPENAI',
  Telegram = 'ARTUS_TELEGRAM',
  XTransit = 'ARTUSX_XTRANSIT',
}

export enum ArtusXErrorEnum {
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
  HTTP_BAD_REQUEST = 'HTTP:BAD_REQUEST',
  HTTP_UNAUTHORIZED = 'HTTP:UNAUTHORIZED',
  HTTP_FORBIDDEN = 'HTTP:FORBIDDEN',
  HTTP_NOT_FODUND = 'HTTP:NOT_FODUND',
  HTTP_METHOD_NOT_ALLOWED = 'HTTP:METHOD_NOT_ALLOWED',
  HTTP_INTERNAL_SERVER_ERROR = 'HTTP:INTERNAL_SERVER_ERROR',
  HTTP_NOT_IMPLEMENTED = 'HTTP:NOT_IMPLEMENTED',
  HTTP_BAD_GATEWAY = 'HTTP:BAD_GATEWAY',
  HTTP_SERVICE_UNAVAILABLE = 'HTTP:SERVICE_UNAVAILABLE',
  HTTP_GATEWAY_TIMEOUT = 'HTTP:GATEWAY_TIMEOUT',

  // artusx
  ARTUSX_UNKNOWN_ERROR = 'ARTUSX:UNKNOWN_ERROR',
}
